### ISSUE TITLE
Tracker cheat codes

### ISSUE THREAD

**Issue by Vivelin** [Vivelin/SMZ3Randomizer#137]
Since this is apparently possible now:

- [ ] Allow tracker to give the player power bombs, missiles, health, etc.
- [ ] Allow tracker to kill the player given specific commands (e.g. "_Hey tracker, fuck you_" — "_Fuck you too, buddy_" followed by player death)
- [ ] Undo should be supported.
- [ ] Must be enabled like hints and spoilers (e.g. "_Hey tracker, enable cheats_", "_Hey tracker, sv_cheats 1_", etc.) or confirmed (imagine Clippy going "📎Do you need some help with that?")
