### ISSUE TITLE
Multiworld Tracker Updates

### ISSUE THREAD

**Issue by MattEqualsCoder** [Vivelin/SMZ3Randomizer#233]
Now that world generation is looking pretty good, tracker needs to be updated to work.

- [x] The DB has been updated to store the world id and all things are saved to the DB at the get go. Tracker should be updated to generate the world off of that rather than recreate the world from the ground up like it currently does.
- [x] Tracking items seems to pull from the current world rather than finding items for the current player
- [x] Hints need to be updated
- [x] Some manual tracking probably needs to be turned off. Some thought will need to be put into this. Perhaps we should turn off all tracking of all built in items? We'll also need to make sure that clearing locations as bullshit is not counted as giving the item to another player. I've adding an "Ignored" flag to the location tracking state to designate manually ignored locations.
