### ISSUE TITLE
Tracker.cs rework

### ISSUE THREAD

**Issue by Vivelin** [Vivelin/SMZ3Randomizer#30]
Tracker.cs is getting kind of chonky. In additon, now that there's multiple ways of tracking things and clearing locations, there needs to be some consistency.

My suggestion is to identify and split up several core tracking functionalities into services, e.g. an Item service for tracking and untracking items, and a Location service for clearing locations.

Tracker.cs will likely still contain the main methods that are called from the voice commands, but the UI will have the option between those and more fine-grained control using the services (but still remain consistent with the rest of tracker).

**Comment by Vivelin** [comment]
Will likely also involve doing something with the SMZ3 Randomizer's Location and the Tracker's new LocationInfo from #20 — they represent the same thing from different perspectives, which does have value, but... I don't know.

**Comment by Vivelin** [comment]
Some ideas:

- [ ] IConfigProvider
- [ ] IWorldProvider
- [ ] ItemService for tracking and untracking items and getting information about items
- [ ] LocationService for clearing locations, seeing what items are there, etc.
- [ ] Some interface for tracker output (e.g. TTS, but possibly none, or even console output)
- [ ] Some sort of ICommand-based system to ensure consistency between voice commands, UI interaction and auto-tracking
