### ISSUE TITLE
Add support for microphone input device selection

### ISSUE THREAD

**Issue by Vivelin** [Vivelin/SMZ3Randomizer#420]
- [ ] Use an audio library, e.g. NAudio, to get a stream to pass into the System.Speech recognition engine
- [ ] Add an option to select the input device

## Nice to have:
- [ ] If the default is selected, automatically switch over input device when the default is changed

**Comment by Vivelin** [comment]
This might be impossible with System.Speech, since both `SetInputToAudioStream` and `SetInputToWaveStream` seem to expect a finite stream, as they seem to be calling the provided Stream's Length property (which will throw, obviously).
